name: Build Windows Portable

on:
  push:
    branches: [ "main", "master" ] # Сборка запустится при пуше в эти ветки
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой на GitHub

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '22'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: git update-index --chmod=+x gradlew
        shell: bash

      - name: Build Portable App Image (EXE + JRE 22)
        # Явно вызываем таску внутри модуля :desktopApp
        run: ./gradlew :desktopApp:packageAppImage --no-daemon

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Compose-App-Windows-Portable
          # Путь к результату сборки внутри модуля :desktopApp
          path: desktopApp/build/compose/binaries/main/appImage/
          retention-days: 5
