name: Build Portable EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest # Запускается на чистой Windows в облаке GitHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Portable App Image
        run: ./gradlew packageAppImage # Собирает портативную папку с EXE

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable-app
          path: build/compose/binaries/main/appImage/
